export const formTypes = [
  {
    id: "2",
    title: "Đơn vắng mặt",
    description:
      "Đơn vắng mặt phát sinh sinh khi bạn muốn vắng một hoặc nhiều ngày làm việc",
    icon: "calendar",
    color: "#f3f2fa",
    iconColor: "#9C27B0",
  },
  {
    id: "3",
    title: "Đơn tăng ca",
    description:
      "Đơn tăng ca phát sinh khi bạn có nhu cầu làm thêm một ca nào đó ngoài ca làm việc đã được phân",
    icon: "clock-circle",
    color: "#fbf2e9",
    iconColor: "#da822f",
  },
  {
    id: "4",
    title: "Đơn quên chấm công",
    description: "Đơn quên chấm công",
    icon: "car",
    color: "#e9f7f8",
    iconColor: "#2cb5d0",
  },
  {
    id: "1",
    title: "Đơn xác thực khuôn mặt",
    description: "Đơn xác thực khuôn mặt",
    icon: "car",
    color: "#ecf7f1",
    iconColor: "#4db47e",
  },
  {
    id: "5",
    title: "Đơn thôi việc",
    description: "Đơn thôi việc",
    icon: "car",
    color: "#ffe9eb",
    iconColor: "#f63331",
  },
  {
    id: "6",
    title: "Đơn về sớm",
    description: "Đơn về sớm",
    icon: "car",
    color: "#ffe9eb",
    iconColor: "#f63331",
  },
  {
    id: "7",
    title: "Đơn khác",
    description: "Các loại đơn khác",
    icon: "file-text",
    color: "#e7e9ee",
    iconColor: "#ffffff",
  },
];
