export enum formCategory {
  FACE_REGISTER = 1,
  ABSENT = 2,
  OT = 3,
  FORGET_TIMEKEEP = 4,
  QUIT_JOB = 5,
  END_EARLY = 6,
  OTHER = 7,
  TRANSFER_JOB = 8,
  LATE = 9,
}

export const formTypes = [
  {
    id: formCategory.ABSENT.toString(),
    title: "Đơn vắng mặt",
    description:
      "Đơn vắng mặt phát sinh khi bạn muốn vắng một hoặc nhiều ngày làm việc",
    icon: "calendar",
    color: "#F3E5F5",
    iconColor: "#9C27B0",
    gradientColors: ["#9C27B0", "#BA68C8"] as const,
  },
  {
    id: formCategory.OT.toString(),
    title: "Đơn tăng ca",
    description:
      "Đơn tăng ca phát sinh khi bạn có nhu cầu làm thêm một ca nào đó ngoài ca làm việc đã được phân",
    icon: "calendar",
    color: "#FFF3E0",
    iconColor: "#FF9800",
    gradientColors: ["#FF9800", "#FFB74D"] as const,
  },
  {
    id: formCategory.FORGET_TIMEKEEP.toString(),
    title: "Đơn quên chấm công",
    description: "Đơn quên chấm công khi bạn không chấm công vào/ra",
    icon: "calendar",
    color: "#E0F7FA",
    iconColor: "#00BCD4",
    gradientColors: ["#00BCD4", "#4DD0E1"] as const,
  },
  {
    id: formCategory.FACE_REGISTER.toString(),
    title: "Đơn xác thực khuôn mặt",
    description: "Đăng ký nhận diện khuôn mặt cho hệ thống",
    icon: "calendar",
    color: "#E8F5E9",
    iconColor: "#4CAF50",
    gradientColors: ["#4CAF50", "#66BB6A"] as const,
  },
  {
    id: formCategory.QUIT_JOB.toString(),
    title: "Đơn thôi việc",
    description: "Đơn xin nghỉ việc và chấm dứt hợp đồng lao động",
    icon: "calendar",
    color: "#FFEBEE",
    iconColor: "#F44336",
    gradientColors: ["#F44336", "#EF5350"] as const,
  },
  {
    id: formCategory.END_EARLY.toString(),
    title: "Đơn về sớm",
    description: "Đơn xin phép về trước giờ tan ca",
    icon: "calendar",
    color: "#FFF9C4",
    iconColor: "#FBC02D",
    gradientColors: ["#FBC02D", "#FDD835"] as const,
  },
  {
    id: formCategory.LATE.toString(),
    title: "Đơn đi muộn",
    description: "Đơn xin phép đi làm muộn",
    icon: "calendar",
    color: "#FFE0B2",
    iconColor: "#F57C00",
    gradientColors: ["#F57C00", "#FB8C00"] as const,
  },
  {
    id: formCategory.OTHER.toString(),
    title: "Đơn khác",
    description: "Các loại đơn khác không thuộc danh mục trên",
    icon: "calendar",
    color: "#ECEFF1",
    iconColor: "#607D8B",
    gradientColors: ["#607D8B", "#78909C"] as const,
  },
];
